[project]
name = "botocore-sign-perf"
version = "0.1.0"
dependencies = [
    "uv>=0.8.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.4",
    "boto3>=1.39.10",
    "botocore>=1.39.10",
    "pyinstrument>=5.0.3",
]

[tool.ruff]
line-length = 120
